### PR TITLE
Autogenerate episodes' list 

### PR DESCRIPTION
**Pull request by dannycolin**
In this PR, I created a Jekyll collections called *_episodes*. With that collections, it is now possible to auto-generate a list of all the episodes on the homepage. 

I also added the configuration to be able to run the website locally in order to test my PR. Finally, I still need to update the documentation (e.g how to add an episode in the README.md) but first I'd like to have your feedback on this PR.

### CODE REVIEW

**Comment by mikeconley** [comment]
Hi dannycolin,

Thanks for this, this is great! A few pieces of feedback:

1. Yes please for documentation. The easier we can make this for people to add new episodes, the better.
2. I also got an un-themed site when I tested this, so presumably I have to install a jekyll theme for it. Documentation for getting the site set up would be really appreciated, in the event that someone else decided to host this somewhere.
3. The episode list has been inverted, and I think that's a great idea - but the most recent stuff at the top.
4. Would it be possible to continue to break up the episodes by the years they took place?

Otherwise, I think this is a great direction. Thank you. :)

**Comment by dannycolin** [comment]
> Yes please for documentation. The easier we can make this for people to add new episodes, the better.

I've updated the CONTRIBUTE.md guide to reflect the change and I've also added instructions to run a local copy. /cc @smurfd for review.

> I also got an un-themed site when I tested this, so presumably I have to install a jekyll theme for it. 

Yes, you need to install the _github-pages_ gem to run the website locally. The following commands should resolve your un-themed issue:

 ```
gem install bundler jekyll
bundle install --path vendor/bundle
bundle exec jekyll serve
```

> Would it be possible to continue to break up the episodes by the years they took place?

Done. :)

**Comment by smurfd** [comment]
Hey. Cool. Im all for making things easier :)
I will try to follow the instructions

**Comment by dannycolin** [comment]
> @smurfd  I will try to follow the instructions

Ok. Let me know if you something is missing or unclear ;).

**Comment by mikeconley** [comment]
Thank you so much!

**Pull request merged**
